import { generateTitleId } from "../../generateTitleId";

export var INTRODUCTION_PAGE_TITLE = "Introduction";
export var INTRODUCTION_PAGE_RELATIVE_PATH = "";

export var INTRODUCTION_PAGE_SETUP_TITLE = "Setup";
export var INTRODUCTION_PAGE_SETUP_ID = generateTitleId(INTRODUCTION_PAGE_SETUP_TITLE);

export var INTRODUCTION_PAGE_EXAMPLE_TITLE = "Example";
export var INTRODUCTION_PAGE_EXAMPLE_ID = generateTitleId(INTRODUCTION_PAGE_EXAMPLE_TITLE);

export var INTRODUCTION_PAGE_MENU_ITEM: TocEntry = {

  title: INTRODUCTION_PAGE_TITLE,
  relativePath: INTRODUCTION_PAGE_RELATIVE_PATH,
  children: [
    { title: INTRODUCTION_PAGE_SETUP_TITLE, relativePath: INTRODUCTION_PAGE_RELATIVE_PATH + "#" + INTRODUCTION_PAGE_SETUP_ID },
    { title: INTRODUCTION_PAGE_EXAMPLE_TITLE, relativePath: INTRODUCTION_PAGE_RELATIVE_PATH + "#" + INTRODUCTION_PAGE_EXAMPLE_ID }
  ]
};