import { generateTitleId } from "../../generateTitleId";

export var INTRODUCTION_TO_OBSERVABLES_PAGE_TITLE = "Introduction to observables";
export var INTRODUCTION_TO_OBSERVABLES_PAGE_RELATIVE_PATH = generateTitleId(INTRODUCTION_TO_OBSERVABLES_PAGE_TITLE);

export var INTRODUCTION_TO_OBSERVABLES_PAGE_OBSERVABLE_INTERFACE_TITLE = "Observable interface";
export var INTRODUCTION_TO_OBSERVABLES_PAGE_OBSERVABLE_INTERFACE_ID = generateTitleId(INTRODUCTION_TO_OBSERVABLES_PAGE_OBSERVABLE_INTERFACE_TITLE);

export var INTRODUCTION_TO_OBSERVABLES_PAGE_MODIFIABLE_OBSERVABLES_TITLE = "Modifiable observables";
export var INTRODUCTION_TO_OBSERVABLES_PAGE_MODIFIABLE_OBSERVABLES_ID = generateTitleId(INTRODUCTION_TO_OBSERVABLES_PAGE_MODIFIABLE_OBSERVABLES_TITLE);

export var INTRODUCTION_TO_OBSERVABLES_PAGE_COMPUTED_OBSERVABLES_TITLE = "Computed observables";
export var INTRODUCTION_TO_OBSERVABLES_PAGE_COMPUTED_OBSERVABLES_ID = generateTitleId(INTRODUCTION_TO_OBSERVABLES_PAGE_COMPUTED_OBSERVABLES_TITLE);

export var INTRODUCTION_TO_OBSERVABLES_PAGE_WHENASYNC_TITLE = "whenAsync()";
export var INTRODUCTION_TO_OBSERVABLES_PAGE_WHENASYNC_ID = "whenasync";

export var INTRODUCTION_TO_OBSERVABLES_PAGE_MENU_ITEM: TocEntry = {

  title: INTRODUCTION_TO_OBSERVABLES_PAGE_TITLE,
  relativePath: INTRODUCTION_TO_OBSERVABLES_PAGE_RELATIVE_PATH,
  children: [
    { title: INTRODUCTION_TO_OBSERVABLES_PAGE_OBSERVABLE_INTERFACE_TITLE, relativePath: INTRODUCTION_TO_OBSERVABLES_PAGE_RELATIVE_PATH + "#" + INTRODUCTION_TO_OBSERVABLES_PAGE_OBSERVABLE_INTERFACE_ID },
    { title: INTRODUCTION_TO_OBSERVABLES_PAGE_MODIFIABLE_OBSERVABLES_TITLE, relativePath: INTRODUCTION_TO_OBSERVABLES_PAGE_RELATIVE_PATH + "#" + INTRODUCTION_TO_OBSERVABLES_PAGE_MODIFIABLE_OBSERVABLES_ID },
    { title: INTRODUCTION_TO_OBSERVABLES_PAGE_COMPUTED_OBSERVABLES_TITLE, relativePath: INTRODUCTION_TO_OBSERVABLES_PAGE_RELATIVE_PATH + "#" + INTRODUCTION_TO_OBSERVABLES_PAGE_COMPUTED_OBSERVABLES_ID },
    { title: INTRODUCTION_TO_OBSERVABLES_PAGE_WHENASYNC_TITLE, relativePath: INTRODUCTION_TO_OBSERVABLES_PAGE_RELATIVE_PATH + "#" + INTRODUCTION_TO_OBSERVABLES_PAGE_WHENASYNC_ID }
  ]
};