import { generateTitleId } from "../../generateTitleId";

export var INTRODUCTION_TO_JSX_PLUS_OBSERVABLES_PAGE_TITLE = "Introduction to JSX + observables";
export var INTRODUCTION_TO_JSX_PLUS_OBSERVABLES_PAGE_RELATIVE_PATH = generateTitleId(INTRODUCTION_TO_JSX_PLUS_OBSERVABLES_PAGE_TITLE);

export var INTRODUCTION_TO_OBSERVABLES_PAGE_MODIFIABLE_OBSERVABLES_TITLE = "Binding to attributes";
export var INTRODUCTION_TO_OBSERVABLES_PAGE_MODIFIABLE_OBSERVABLES_ID = generateTitleId(INTRODUCTION_TO_OBSERVABLES_PAGE_MODIFIABLE_OBSERVABLES_TITLE);

export var INTRODUCTION_TO_JSX_PLUS_OBSERVABLES_PAGE_MENU_ITEM: TocEntry = {

  title: INTRODUCTION_TO_JSX_PLUS_OBSERVABLES_PAGE_TITLE,
  relativePath: INTRODUCTION_TO_JSX_PLUS_OBSERVABLES_PAGE_RELATIVE_PATH,
  children: [

  ]
};